/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generate sidebar from docs folder
    },
    // Additional manual entries for specific ordering
    {
      type: 'category',
      label: 'Physical AI & Humanoid Robotics Textbook',
      items: [
        'intro',
        {
          type: 'category',
          label: 'Module 1: ROS 2 Nervous System',
          items: [
            'module1-ros2-nervous-system/index',
            // 'module1-ros2-nervous-system/chapter1-fundamentals',
            // 'module1-ros2-nervous-system/chapter2-advanced-patterns',
            // 'module1-ros2-nervous-system/chapter3-robot-integration',
          ],
        },
        {
          type: 'category',
          label: 'Module 2: Digital Twin Simulation',
          items: [
            'module2-digital-twin-simulation/index',
            // 'module2-digital-twin-simulation/chapter1-sim-fundamentals',
            // 'module2-digital-twin-simulation/chapter2-robot-modeling',
            // 'module2-digital-twin-simulation/chapter3-advanced-sim',
          ],
        },
        {
          type: 'category',
          label: 'Module 3: AI Brain (NVIDIA Isaac)',
          items: [
            'module3-ai-brain-isaac/index',
            // 'module3-ai-brain-isaac/chapter1-isaac-fundamentals',
            // 'module3-ai-brain-isaac/chapter2-navigation-planning',
            // 'module3-ai-brain-isaac/chapter3-manipulation-control',
          ],
        },
        {
          type: 'category',
          label: 'Module 4: Vision-Language-Action Robotics',
          items: [
            'module4-vla-robotics/index',
            // 'module4-vla-robotics/chapter1-vla-fundamentals',
            // 'module4-vla-robotics/chapter2-multimodal-perception',
            // 'module4-vla-robotics/chapter3-task-planning-execution',
          ],
        },
        'weekly-roadmap',
        {
          type: 'category',
          label: 'Additional Materials',
          items: [
            'index',
            'hardware',
            'cloud',
            'final_materials',
          ],
        },
      ],
    },
  ],
};

module.exports = sidebars;